### PR TITLE
Notifications testing code

### PR DESCRIPTION
**Pull request by douglowder**
- Add `expo-notifications` package
- Add Google services to config
- Add a rough UI for testing

This works in local testing with my own Firebase setup with package name changed to `com.douglowderexpo.microfoam`

### CODE REVIEW

**Comment by douglowder** [comment]
TBD, maybe add a lot of `Log.i('MicrofoamNotifications', ...)` lines in a patch to `expo-notifications`, so we have better visibility into which of our APIs are actually getting called.

**Comment by douglowder** [comment]
@brentvatne before we merge this, you will want to take steps to set up your `google-services.json` file and your Firebase push notifications private key, and follow the instructions here:

https://docs.expo.dev/push-notifications/fcm-credentials/

**Comment by douglowder** [comment]
image

**Review by christopherwalter — APPROVED** [review]
LGTM but I'll defer to @brentvatne for technical thoughts. Hopefully this gives us some insight into prod, thanks for putting it together @douglowder!

**Pull request merged**
